In [1]:
import pandas as pd
import numpy as np

In [46]:
file_flag = input("请输入股票名：")
if file_flag == '1' or True:
    csv_file = r'/home/cpj/python/data/lab2/data/600519.csv'

    csv = pd.read_csv(csv_file, encoding='gb18030')

    df = pd.DataFrame(csv)
    date =  '2020-09-17'
    test1 = df[df['日期']==date_]
    print(test1)

请输入股票名：
Empty DataFrame
Columns: [日期, 股票代码, 名称, 收盘价, 最高价, 最低价, 开盘价, 前收盘, 涨跌额, 涨跌幅, 换手率, 成交量, 成交金额, 总市值, 流通市值]
Index: []

In [57]:
file_flag = input("请输入股票名：")
if file_flag == '1' or True:
    csv_file = r'/home/cpj/python/data/lab2/data/600519.csv'

    csv = pd.read_csv(csv_file, encoding='gb18030')

    df = pd.DataFrame(csv)
    date =  input("输入日期")
    test1 = df[df['日期']==date_]
    print(test1)

请输入股票名：
1
输入日期
2020-09-17

           日期     股票代码    名称      收盘价     最高价     最低价     开盘价     前收盘     涨跌额  \
2  2020-09-17  '600519  贵州茅台  1670.52  1700.0  1658.0  1700.0  1725.1  -54.58

       涨跌幅     换手率      成交量          成交金额           总市值          流通市值
2  -3.1639  0.5069  6367985  1.068335e+10  2.098504e+12  2.098504e+12

In [57]:
print('请输入股票名：\n1\n输入日期\n2020-09-17\n')
print(df[df['日期']=='2020-09-17'])

请输入股票名：
1
输入日期
2020-09-17

           日期     股票代码    名称      收盘价     最高价     最低价     开盘价     前收盘     涨跌额  \
2  2020-09-17  '600519  贵州茅台  1670.52  1700.0  1658.0  1700.0  1725.1  -54.58

       涨跌幅     换手率      成交量          成交金额           总市值          流通市值
2  -3.1639  0.5069  6367985  1.068335e+10  2.098504e+12  2.098504e+12

In [61]:
flag = (float)(input())
df[df['收盘价']>flag]

1800

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
14,2020-09-01,'600519,贵州茅台,1801.98,1802.0,1775.01,1792.0,1786.5,15.48,0.8665,0.2519,3163992,5.661594e+09,2.263643e+12,2.263643e+12

In [69]:
flag = input()
df[df['涨跌幅']>flag]

9

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
1324,2015-04-21,'600519,贵州茅台,257.43,257.43,240.0,240.0,234.03,23.4,9.9987,1.0718,12240188,3.039244e+09,2.939845e+11,2.939845e+11
1893,2012-12-10,'600519,贵州茅台,0.00,0.00,0.0,0.0,198.79,None,None,0.0000,0,0.000000e+00,2.063798e+11,2.063798e+11
1958,2012-09-03,'600519,贵州茅台,0.00,0.00,0.0,0.0,219.76,None,None,0.0000,0,0.000000e+00,2.281504e+11,2.281504e+11
2026,2012-05-29,'600519,贵州茅台,0.00,0.00,0.0,0.0,225.49,None,None,0.0000,0,0.000000e+00,2.340992e+11,2.340992e+11
2271,2011-05-25,'600519,贵州茅台,0.00,0.00,0.0,0.0,194.61,None,None,0.0000,0,0.000000e+00,1.836729e+11,1.836729e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4067,2003-12-29,'600519,贵州茅台,0.00,0.00,0.0,0.0,25.28,None,None,0.0000,0,0.000000e+00,7.647200e+09,2.187099e+09
4204,2003-06-12,'600519,贵州茅台,0.00,0.00,0.0,0.0,25.61,None,None,0.0000,0,0.000000e+00,7.042750e+09,2.014226e+09
4328,2002-11-29,'600519,贵州茅台,0.00,0.00,0.0,0.0,26.28,None,None,0.0000,0,0.000000e+00,7.227000e+09,2.066922e+09
4435,2002-06-25,'600519,贵州茅台,0.00,0.00,0.0,0.0,38.18,None,None,0.0000,0,0.000000e+00,9.545000e+09,2.729870e+09
4516,2002-02-25,'600519,贵州茅台,0.00,0.00,0.0,0.0,37.65,None,None,0.0000,0,0.000000e+00,9.412500e+09,2.691975e+09

In [71]:
flag = (int)(input())
df[df['成交量']>flag]

12222222

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
159,2020-02-03,'600519,贵州茅台,1003.92,1010.68,980.00,985.00,1052.80,-48.88,-4.6429,0.9827,12344288,1.231499e+10,1.261122e+12,1.261122e+12
174,2020-01-03,'600519,贵州茅台,1078.56,1117.00,1076.90,1117.00,1130.00,-51.44,-4.5522,1.0374,13031878,1.426638e+10,1.354885e+12,1.354885e+12
175,2020-01-02,'600519,贵州茅台,1130.00,1145.06,1116.00,1128.00,1183.00,-53.0,-4.4801,1.1789,14809916,1.669684e+10,1.419504e+12,1.419504e+12
340,2019-05-06,'600519,贵州茅台,906.00,935.00,893.00,925.50,974.00,-68.0,-6.9815,1.0755,13509968,1.229940e+10,1.138115e+12,1.138115e+12
463,2018-10-30,'600519,贵州茅台,524.00,543.00,509.02,510.00,549.09,-25.09,-4.5694,1.6271,20439667,1.066339e+10,6.582476e+11,6.582476e+11
468,2018-10-23,'600519,贵州茅台,641.74,689.00,635.00,689.00,693.00,-51.26,-7.3968,0.9800,12311273,8.076619e+09,8.061524e+11,8.061524e+11
664,2017-12-28,'600519,贵州茅台,718.69,719.90,671.32,687.00,664.18,54.51,8.2071,0.9882,12414107,8.656876e+09,9.028168e+11,9.028168e+11
690,2017-11-22,'600519,贵州茅台,650.52,688.00,650.00,677.00,677.25,-26.73,-3.9468,1.0229,12849826,8.528143e+09,8.171818e+11,8.171818e+11
693,2017-11-17,'600519,贵州茅台,690.25,709.00,677.77,696.00,719.11,-28.86,-4.0133,0.9860,12386124,8.548748e+09,8.670905e+11,8.670905e+11
1236,2015-08-25,'600519,贵州茅台,176.59,182.51,166.20,167.46,169.64,6.95,4.0969,0.9798,12308058,2.165824e+09,2.218320e+11,2.218320e+11
1267,2015-07-13,'600519,贵州茅台,257.75,265.58,251.00,258.00,265.59,-7.84,-2.9519,1.3041,14892616,3.838169e+09,2.943500e+11,2.943500e+11
1268,2015-07-10,'600519,贵州茅台,265.59,283.00,251.96,257.00,257.94,7.65,2.9658,2.2430,25614930,6.888908e+09,3.033032e+11,3.033032e+11
1269,2015-07-09,'600519,贵州茅台,257.94,260.41,233.00,236.86,236.86,21.08,8.8998,1.2102,13820334,3.409951e+09,2.945670e+11,2.945670e+11
1270,2015-07-08,'600519,贵州茅台,236.86,244.99,219.76,229.00,244.18,-7.32,-2.9978,2.5319,28914054,6.738027e+09,2.704936e+11,2.704936e+11
1271,2015-07-07,'600519,贵州茅台,244.18,256.58,239.50,250.00,254.04,-9.86,-3.8813,1.4673,16756224,4.121732e+09,2.788531e+11,2.788531e+11
1272,2015-07-06,'600519,贵州茅台,254.04,267.99,239.50,267.95,249.81,4.23,1.6933,2.3888,27279966,7.012491e+09,2.901132e+11,2.901132e+11
1276,2015-06-30,'600519,贵州茅台,257.65,259.82,246.00,246.64,246.64,11.01,4.464,1.1059,12629819,3.205286e+09,2.942358e+11,2.942358e+11
1277,2015-06-29,'600519,贵州茅台,246.64,256.50,227.80,248.37,242.45,4.19,1.7282,1.4455,16507167,4.057070e+09,2.816624e+11,2.816624e+11
1323,2015-04-22,'600519,贵州茅台,263.89,269.00,257.11,268.80,257.43,6.46,2.5094,1.1789,13463506,3.543577e+09,3.013619e+11,3.013619e+11
1324,2015-04-21,'600519,贵州茅台,257.43,257.43,240.00,240.00,234.03,23.4,9.9987,1.0718,12240188,3.039244e+09,2.939845e+11,2.939845e+11
1325,2015-04-20,'600519,贵州茅台,234.03,245.70,229.00,230.00,232.56,1.47,0.6321,1.1435,13058871,3.118765e+09,2.672618e+11,2.672618e+11
1326,2015-04-17,'600519,贵州茅台,232.56,248.70,228.28,238.90,226.27,6.29,2.7799,1.6821,19209491,4.577504e+09,2.655831e+11,2.655831e+11
1333,2015-04-08,'600519,贵州茅台,204.50,210.68,201.59,202.50,200.67,3.83,1.9086,1.1896,13585716,2.798382e+09,2.335386e+11,2.335386e+11
1411,2014-12-09,'600519,贵州茅台,172.86,186.62,171.50,172.00,172.97,-0.11,-0.0636,1.3300,15189028,2.713372e+09,1.974058e+11,1.974058e+11
1427,2014-11-17,'600519,贵州茅台,160.05,168.00,160.00,168.00,157.29,2.76,1.7547,1.3171,15041623,2.451674e+09,1.827768e+11,1.827768e+11
1718,2013-09-03,'600519,贵州茅台,151.66,152.80,149.00,151.00,151.92,-0.26,-0.1711,1.1868,12321105,1.855979e+09,1.574504e+11,1.574504e+11
1719,2013-09-02,'600519,贵州茅台,151.92,160.80,151.90,160.80,168.78,-16.86,-9.9893,2.1670,22497074,3.438419e+09,1.577203e+11,1.577203e+11
1861,2013-01-28,'600519,贵州茅台,178.50,187.80,178.00,186.00,189.05,-10.55,-5.5805,1.5247,15829058,2.857093e+09,1.853151e+11,1.853151e+11
2400,2010-11-12,'600519,贵州茅台,177.53,188.08,175.52,175.55,175.92,1.61,0.9152,1.3403,12650029,2.298576e+09,1.675528e+11,1.675528e+11
2402,2010-11-10,'600519,贵州茅台,179.73,182.45,166.50,166.60,165.86,13.87,8.3625,1.5894,15000509,2.670067e+09,1.696292e+11,1.696292e+11
2547,2010-04-02,'600519,贵州茅台,152.63,158.00,151.60,158.00,160.06,-7.43,-4.642,1.6347,15428170,2.359759e+09,1.440522e+11,1.440522e+11
3256,2007-05-14,'600519,贵州茅台,94.39,100.78,92.18,93.60,92.00,2.39,2.5978,4.3620,13187045,1.263779e+09,8.908528e+10,2.853580e+10
3259,2007-05-09,'600519,贵州茅台,92.00,96.51,89.90,96.50,96.50,-4.5,-4.6632,5.0204,15177660,1.394029e+09,8.682960e+10,2.781326e+10
3486,2006-05-31,'600519,G 茅 台,48.02,51.90,46.88,48.45,48.39,-0.37,-0.7646,5.0189,15173103,7.474115e+08,4.532128e+10,1.451731e+10
3487,2006-05-30,'600519,G 茅 台,48.39,48.39,45.61,47.10,43.99,4.4,10.0023,4.5898,13875854,6.647766e+08,4.567048e+10,1.462917e+10
3490,2006-05-25,'600519,G 茅 台,39.59,47.00,38.10,45.00,44.97,-5.38,-11.9635,6.5533,19811697,8.119087e+08,3.736504e+10,1.196877e+10
4627,2001-08-28,'600519,贵州茅台,36.86,37.00,34.61,34.99,35.55,1.31,3.685,18.1326,12964779,4.634631e+08,9.215000e+09,2.635490e+09
4628,2001-08-27,'600519,贵州茅台,35.55,37.78,32.85,34.51,31.39,4.16,13.2526,56.8277,40631800,1.410347e+09,8.887500e+09,2.541825e+09

In [71]:
flag = (int)(input())
df[df['成交量']>flag]

12222222

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
159,2020-02-03,'600519,贵州茅台,1003.92,1010.68,980.00,985.00,1052.80,-48.88,-4.6429,0.9827,12344288,1.231499e+10,1.261122e+12,1.261122e+12
174,2020-01-03,'600519,贵州茅台,1078.56,1117.00,1076.90,1117.00,1130.00,-51.44,-4.5522,1.0374,13031878,1.426638e+10,1.354885e+12,1.354885e+12
175,2020-01-02,'600519,贵州茅台,1130.00,1145.06,1116.00,1128.00,1183.00,-53.0,-4.4801,1.1789,14809916,1.669684e+10,1.419504e+12,1.419504e+12
340,2019-05-06,'600519,贵州茅台,906.00,935.00,893.00,925.50,974.00,-68.0,-6.9815,1.0755,13509968,1.229940e+10,1.138115e+12,1.138115e+12
463,2018-10-30,'600519,贵州茅台,524.00,543.00,509.02,510.00,549.09,-25.09,-4.5694,1.6271,20439667,1.066339e+10,6.582476e+11,6.582476e+11
468,2018-10-23,'600519,贵州茅台,641.74,689.00,635.00,689.00,693.00,-51.26,-7.3968,0.9800,12311273,8.076619e+09,8.061524e+11,8.061524e+11
664,2017-12-28,'600519,贵州茅台,718.69,719.90,671.32,687.00,664.18,54.51,8.2071,0.9882,12414107,8.656876e+09,9.028168e+11,9.028168e+11
690,2017-11-22,'600519,贵州茅台,650.52,688.00,650.00,677.00,677.25,-26.73,-3.9468,1.0229,12849826,8.528143e+09,8.171818e+11,8.171818e+11
693,2017-11-17,'600519,贵州茅台,690.25,709.00,677.77,696.00,719.11,-28.86,-4.0133,0.9860,12386124,8.548748e+09,8.670905e+11,8.670905e+11
1236,2015-08-25,'600519,贵州茅台,176.59,182.51,166.20,167.46,169.64,6.95,4.0969,0.9798,12308058,2.165824e+09,2.218320e+11,2.218320e+11
1267,2015-07-13,'600519,贵州茅台,257.75,265.58,251.00,258.00,265.59,-7.84,-2.9519,1.3041,14892616,3.838169e+09,2.943500e+11,2.943500e+11
1268,2015-07-10,'600519,贵州茅台,265.59,283.00,251.96,257.00,257.94,7.65,2.9658,2.2430,25614930,6.888908e+09,3.033032e+11,3.033032e+11
1269,2015-07-09,'600519,贵州茅台,257.94,260.41,233.00,236.86,236.86,21.08,8.8998,1.2102,13820334,3.409951e+09,2.945670e+11,2.945670e+11
1270,2015-07-08,'600519,贵州茅台,236.86,244.99,219.76,229.00,244.18,-7.32,-2.9978,2.5319,28914054,6.738027e+09,2.704936e+11,2.704936e+11
1271,2015-07-07,'600519,贵州茅台,244.18,256.58,239.50,250.00,254.04,-9.86,-3.8813,1.4673,16756224,4.121732e+09,2.788531e+11,2.788531e+11
1272,2015-07-06,'600519,贵州茅台,254.04,267.99,239.50,267.95,249.81,4.23,1.6933,2.3888,27279966,7.012491e+09,2.901132e+11,2.901132e+11
1276,2015-06-30,'600519,贵州茅台,257.65,259.82,246.00,246.64,246.64,11.01,4.464,1.1059,12629819,3.205286e+09,2.942358e+11,2.942358e+11
1277,2015-06-29,'600519,贵州茅台,246.64,256.50,227.80,248.37,242.45,4.19,1.7282,1.4455,16507167,4.057070e+09,2.816624e+11,2.816624e+11
1323,2015-04-22,'600519,贵州茅台,263.89,269.00,257.11,268.80,257.43,6.46,2.5094,1.1789,13463506,3.543577e+09,3.013619e+11,3.013619e+11
1324,2015-04-21,'600519,贵州茅台,257.43,257.43,240.00,240.00,234.03,23.4,9.9987,1.0718,12240188,3.039244e+09,2.939845e+11,2.939845e+11
1325,2015-04-20,'600519,贵州茅台,234.03,245.70,229.00,230.00,232.56,1.47,0.6321,1.1435,13058871,3.118765e+09,2.672618e+11,2.672618e+11
1326,2015-04-17,'600519,贵州茅台,232.56,248.70,228.28,238.90,226.27,6.29,2.7799,1.6821,19209491,4.577504e+09,2.655831e+11,2.655831e+11
1333,2015-04-08,'600519,贵州茅台,204.50,210.68,201.59,202.50,200.67,3.83,1.9086,1.1896,13585716,2.798382e+09,2.335386e+11,2.335386e+11
1411,2014-12-09,'600519,贵州茅台,172.86,186.62,171.50,172.00,172.97,-0.11,-0.0636,1.3300,15189028,2.713372e+09,1.974058e+11,1.974058e+11
1427,2014-11-17,'600519,贵州茅台,160.05,168.00,160.00,168.00,157.29,2.76,1.7547,1.3171,15041623,2.451674e+09,1.827768e+11,1.827768e+11
1718,2013-09-03,'600519,贵州茅台,151.66,152.80,149.00,151.00,151.92,-0.26,-0.1711,1.1868,12321105,1.855979e+09,1.574504e+11,1.574504e+11
1719,2013-09-02,'600519,贵州茅台,151.92,160.80,151.90,160.80,168.78,-16.86,-9.9893,2.1670,22497074,3.438419e+09,1.577203e+11,1.577203e+11
1861,2013-01-28,'600519,贵州茅台,178.50,187.80,178.00,186.00,189.05,-10.55,-5.5805,1.5247,15829058,2.857093e+09,1.853151e+11,1.853151e+11
2400,2010-11-12,'600519,贵州茅台,177.53,188.08,175.52,175.55,175.92,1.61,0.9152,1.3403,12650029,2.298576e+09,1.675528e+11,1.675528e+11
2402,2010-11-10,'600519,贵州茅台,179.73,182.45,166.50,166.60,165.86,13.87,8.3625,1.5894,15000509,2.670067e+09,1.696292e+11,1.696292e+11
2547,2010-04-02,'600519,贵州茅台,152.63,158.00,151.60,158.00,160.06,-7.43,-4.642,1.6347,15428170,2.359759e+09,1.440522e+11,1.440522e+11
3256,2007-05-14,'600519,贵州茅台,94.39,100.78,92.18,93.60,92.00,2.39,2.5978,4.3620,13187045,1.263779e+09,8.908528e+10,2.853580e+10
3259,2007-05-09,'600519,贵州茅台,92.00,96.51,89.90,96.50,96.50,-4.5,-4.6632,5.0204,15177660,1.394029e+09,8.682960e+10,2.781326e+10
3486,2006-05-31,'600519,G 茅 台,48.02,51.90,46.88,48.45,48.39,-0.37,-0.7646,5.0189,15173103,7.474115e+08,4.532128e+10,1.451731e+10
3487,2006-05-30,'600519,G 茅 台,48.39,48.39,45.61,47.10,43.99,4.4,10.0023,4.5898,13875854,6.647766e+08,4.567048e+10,1.462917e+10
3490,2006-05-25,'600519,G 茅 台,39.59,47.00,38.10,45.00,44.97,-5.38,-11.9635,6.5533,19811697,8.119087e+08,3.736504e+10,1.196877e+10
4627,2001-08-28,'600519,贵州茅台,36.86,37.00,34.61,34.99,35.55,1.31,3.685,18.1326,12964779,4.634631e+08,9.215000e+09,2.635490e+09
4628,2001-08-27,'600519,贵州茅台,35.55,37.78,32.85,34.51,31.39,4.16,13.2526,56.8277,40631800,1.410347e+09,8.887500e+09,2.541825e+09

In [73]:
flag = (int)(input())
df[df['成交金额']>flag]

1000000000

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
0,2020-09-21,'600519,贵州茅台,1666.80,1692.76,1666.66,1692.76,1695.00,-28.2,-1.6637,0.1787,2244407,3.756765e+09,2.093830e+12,2.093830e+12
1,2020-09-18,'600519,贵州茅台,1695.00,1695.00,1635.01,1665.00,1670.52,24.48,1.4654,0.3757,4720140,7.853673e+09,2.129255e+12,2.129255e+12
2,2020-09-17,'600519,贵州茅台,1670.52,1700.00,1658.00,1700.00,1725.10,-54.58,-3.1639,0.5069,6367985,1.068335e+10,2.098504e+12,2.098504e+12
3,2020-09-16,'600519,贵州茅台,1725.10,1764.81,1719.00,1760.00,1760.00,-34.9,-1.983,0.1792,2251598,3.916458e+09,2.167067e+12,2.167067e+12
4,2020-09-15,'600519,贵州茅台,1760.00,1769.99,1747.75,1769.99,1766.00,-6.0,-0.3398,0.1657,2082087,3.654872e+09,2.210908e+12,2.210908e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532,2010-04-26,'600519,贵州茅台,136.93,139.58,136.90,139.00,143.83,-6.9,-4.7973,1.1341,10703613,1.480340e+09,1.292345e+11,1.292345e+11
2547,2010-04-02,'600519,贵州茅台,152.63,158.00,151.60,158.00,160.06,-7.43,-4.642,1.6347,15428170,2.359759e+09,1.440522e+11,1.440522e+11
3256,2007-05-14,'600519,贵州茅台,94.39,100.78,92.18,93.60,92.00,2.39,2.5978,4.3620,13187045,1.263779e+09,8.908528e+10,2.853580e+10
3259,2007-05-09,'600519,贵州茅台,92.00,96.51,89.90,96.50,96.50,-4.5,-4.6632,5.0204,15177660,1.394029e+09,8.682960e+10,2.781326e+10
4628,2001-08-27,'600519,贵州茅台,35.55,37.78,32.85,34.51,31.39,4.16,13.2526,56.8277,40631800,1.410347e+09,8.887500e+09,2.541825e+09

In [64]:
df.iloc[1,10].dtype

dtype('float64')

In [73]:
flag = (int)(input())
df[df['成交金额']>flag]

1000000000

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
0,2020-09-21,'600519,贵州茅台,1666.80,1692.76,1666.66,1692.76,1695.00,-28.2,-1.6637,0.1787,2244407,3.756765e+09,2.093830e+12,2.093830e+12
1,2020-09-18,'600519,贵州茅台,1695.00,1695.00,1635.01,1665.00,1670.52,24.48,1.4654,0.3757,4720140,7.853673e+09,2.129255e+12,2.129255e+12
2,2020-09-17,'600519,贵州茅台,1670.52,1700.00,1658.00,1700.00,1725.10,-54.58,-3.1639,0.5069,6367985,1.068335e+10,2.098504e+12,2.098504e+12
3,2020-09-16,'600519,贵州茅台,1725.10,1764.81,1719.00,1760.00,1760.00,-34.9,-1.983,0.1792,2251598,3.916458e+09,2.167067e+12,2.167067e+12
4,2020-09-15,'600519,贵州茅台,1760.00,1769.99,1747.75,1769.99,1766.00,-6.0,-0.3398,0.1657,2082087,3.654872e+09,2.210908e+12,2.210908e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532,2010-04-26,'600519,贵州茅台,136.93,139.58,136.90,139.00,143.83,-6.9,-4.7973,1.1341,10703613,1.480340e+09,1.292345e+11,1.292345e+11
2547,2010-04-02,'600519,贵州茅台,152.63,158.00,151.60,158.00,160.06,-7.43,-4.642,1.6347,15428170,2.359759e+09,1.440522e+11,1.440522e+11
3256,2007-05-14,'600519,贵州茅台,94.39,100.78,92.18,93.60,92.00,2.39,2.5978,4.3620,13187045,1.263779e+09,8.908528e+10,2.853580e+10
3259,2007-05-09,'600519,贵州茅台,92.00,96.51,89.90,96.50,96.50,-4.5,-4.6632,5.0204,15177660,1.394029e+09,8.682960e+10,2.781326e+10
4628,2001-08-27,'600519,贵州茅台,35.55,37.78,32.85,34.51,31.39,4.16,13.2526,56.8277,40631800,1.410347e+09,8.887500e+09,2.541825e+09

In [74]:
def marge(csv_list, outputfile):
    for inputfile in csv_list:
        f = open(inputfile, 'r', encoding='gb18030',errors='ignore')
        data = pd.read_csv(f,encoding='gb18030')
        data.to_csv(outputfile, mode='a', index=False)
    print('完成合并')
 
 #去重保留一个表头
def distinct(file):
    df = pd.read_csv(file, header=None)
    datalist = df.drop_duplicates()
    datalist.to_csv( index=False, header=False)
    print('完成去重')

In [79]:
csv_file = r'/home/cpj/python/data/lab2/data/margin.csv'
csv = pd.read_csv(csv_file)
df = pd.DataFrame(csv)

FileNotFoundError: [Errno 2] No such file or directory: '/home/cpj/python/data/lab2/data/margin.csv'

In [78]:
df

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
0,2020-09-21,'600519,贵州茅台,1666.8,1692.76,1666.66,1692.76,1695.0,-28.2,-1.6637,0.1787,2244407,3756765108.0,2093830493040.0,2093830493040.0
1,2020-09-18,'600519,贵州茅台,1695.0,1695.0,1635.01,1665.0,1670.52,24.48,1.4654,0.3757,4720140,7853673241.0,2129255271000.0,2129255271000.0
2,2020-09-17,'600519,贵州茅台,1670.52,1700.0,1658.0,1700.0,1725.1,-54.58,-3.1639,0.5069,6367985,10683350187.0,2098503548860.0,2098503548860.0
3,2020-09-16,'600519,贵州茅台,1725.1,1764.81,1719.0,1760.0,1760.0,-34.9,-1.983,0.1792,2251598,3916457762.0,2167066824780.0,2167066824780.0
4,2020-09-15,'600519,贵州茅台,1760.0,1769.99,1747.75,1769.99,1766.0,-6.0,-0.3398,0.1657,2082087,3654872009.0,2210908128000.0,2210908128000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10062,1998-05-04,'000858,五 粮 液,59.02,59.02,55.0,55.1,53.65,5.37,10.0093,6.8347,4920974,285312925.33,18886400000.0,4249440000.0
10063,1998-04-30,'000858,五 粮 液,53.65,54.2,53.2,53.3,53.3,0.35,0.6567,3.3135,2385686,127942178.11,17168000000.0,3862800000.0
10064,1998-04-29,'000858,五 粮 液,53.3,54.98,52.9,54.97,54.19,-0.89,-1.6424,4.7128,3393230,181927515.95,17056000000.0,3837600000.0
10065,1998-04-28,'000858,五 粮 液,54.19,56.5,53.6,54.0,53.57,0.62,1.1574,9.397,6765827,371571836.1,17340800000.0,3901680000.0
10066,1998-04-27,'000858,五 粮 液,53.57,57.0,29.77,29.77,0.0,None,None,47.4487,34163076,1846204586.12,17142400000.0,3857040000.0

In [80]:
flag = input()
df[df['涨跌幅']>flag]

10

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
39,2020-07-28,'600519,贵州茅台,1670.0,1680.0,1630.0,1630.0,1622.55,47.45,2.9244,0.4371,5491152,9133721867.0,2097850326000.0,2097850326000.0
46,2020-07-17,'600519,贵州茅台,1648.05,1672.59,1620.0,1620.0,1614.0,34.05,2.1097,0.5246,6590206,10863420089.0,2070276784290.0,2070276784290.0
50,2020-07-13,'600519,贵州茅台,1781.99,1787.0,1714.68,1714.68,1713.85,68.14,3.9758,0.4834,6072716,10679460274.0,2238531917620.0,2238531917620.0
54,2020-07-07,'600519,贵州茅台,1688.0,1744.82,1601.0,1603.09,1600.0,88.0,5.5,0.5307,6666393,11219852098.0,2120461886400.0,2120461886400.0
55,2020-07-06,'600519,贵州茅台,1600.0,1616.0,1531.81,1538.0,1541.79,58.21,3.7755,0.4125,5182196,8228068998.0,2009916480000.0,2009916480000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10035,1998-06-10,'000858,五 粮 液,57.01,58.0,55.5,55.5,55.57,1.44,2.5913,0.7026,505855,28690455.8,18243200000.0,4104720000.0
10060,1998-05-06,'000858,五 粮 液,65.73,66.0,61.8,62.2,62.66,3.07,4.8995,6.162000000000001,4436626,283147678.47,21033600000.0,4732560000.0
10061,1998-05-05,'000858,五 粮 液,62.66,64.9,61.61,62.88,59.02,3.64,6.1674,11.6799,8409522,532130549.21,20051200000.0,4511520000.0
10062,1998-05-04,'000858,五 粮 液,59.02,59.02,55.0,55.1,53.65,5.37,10.0093,6.8347,4920974,285312925.33,18886400000.0,4249440000.0
10066,1998-04-27,'000858,五 粮 液,53.57,57.0,29.77,29.77,0.0,None,None,47.4487,34163076,1846204586.12,17142400000.0,3857040000.0

In [82]:
flag = input("请输入日期：\n2019-08-08")
df[df['日期']==flag]

请输入日期：
2019-08-08

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
273,2019-08-08,'600519,贵州茅台,971.68,974.0,952.0,953.5,945.0,26.68,2.8233,0.3089,3880813,3755086990.0,1220622278300.0,1220622278300.0
4903,2019-08-08,'000858,五 粮 液,120.52,121.61,119.26,119.49,118.88,1.64,1.3795,0.6643,25217971,3043542051.97,467811396763.0,457489909094.0

In [84]:
flag = input()
df[df['成交量']>flag]

9000000

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
337,2019-05-09,'600519,贵州茅台,858.81,879.87,842.5,875.0,884.4,-25.59,-2.8935,0.7287,9154515,7863312116.0,1078835232620.0,1078835232620.0
362,2019-03-29,'600519,贵州茅台,853.99,866.68,830.17,835.0,806.8,47.19,5.849,0.7239,9093396,7702154797.0,1072780359220.0,1072780359220.0
461,2018-11-01,'600519,贵州茅台,563.0,585.5,551.25,555.0,548.9,14.1,2.5688,0.7809999999999999,9810672,5581027253.0,707239361400.0,707239361400.0
462,2018-10-31,'600519,贵州茅台,548.9,555.0,522.0,527.0,524.0,24.9,4.7519,0.7713,9688482,5239853122.0,689526972420.0,689526972420.0
476,2018-10-11,'600519,贵州茅台,644.99,668.94,635.01,635.01,670.92,-25.93,-3.8648,0.7290000000000001,9158196,5953169079.0,810235019022.0,810235019022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9899,1998-12-21,'000858,五 粮 液,40.89,41.37,40.38,40.8,41.0,-0.11,-0.2683,0.11900000000000001,95205,3898690.75,13084800000.0,3271200000.0
9983,1998-08-21,'000858,五 粮 液,40.99,41.14,38.9,39.19,39.23,1.76,4.4864,1.3767,991200,39868897.34,13116800000.0,2951280000.0
9986,1998-08-18,'000858,五 粮 液,37.85,39.5,36.01,36.59,37.05,0.8,2.1592,1.2716,915534,34968100.88,12112000000.0,2725200000.0
10021,1998-06-30,'000858,五 粮 液,50.7,53.5,50.5,53.5,53.35,-2.65,-4.9672,1.2599,907130,47227032.08,16224000000.0,3650400000.0
10050,1998-05-20,'000858,五 粮 液,60.89,62.3,60.85,62.0,62.33,-1.44,-2.3103,1.2802,921740,56580399.29,19484800000.0,4384080000.0

In [87]:
flag = (input())
df[df['成交金额']>flag]

8902012

,日期,股票代码,名称,收盘价,最高价,最低价,开盘价,前收盘,涨跌额,涨跌幅,换手率,成交量,成交金额,总市值,流通市值
39,2020-07-28,'600519,贵州茅台,1670.0,1680.0,1630.0,1630.0,1622.55,47.45,2.9244,0.4371,5491152,9133721867.0,2097850326000.0,2097850326000.0
53,2020-07-08,'600519,贵州茅台,1681.34,1719.0,1660.0,1680.0,1688.0,-6.66,-0.3945,0.4233,5316998,8963189092.0,2112095609050.0,2112095609050.0
198,2019-11-29,'600519,贵州茅台,1129.0,1165.5,1112.89,1165.5,1175.8,-46.8,-3.9803,0.6559,8239732,9338326554.0,1418247316200.0,1418247316200.0
249,2019-09-11,'600519,贵州茅台,1069.52,1119.97,1068.0,1119.22,1123.85,-54.33,-4.8343,0.6505,8171654,8904690560.0,1343528671060.0,1343528671060.0
339,2019-05-07,'600519,贵州茅台,890.0,913.94,870.22,893.28,906.0,-16.0,-1.766,0.8027,10083726,9045117765.0,1118016042000.0,1118016042000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,1998-10-29,'000858,五 粮 液,38.91,39.43,38.68,39.0,38.94,-0.03,-0.077,0.2905,232365,9042487.75,12451200000.0,3112800000.0
9943,1998-10-20,'000858,五 粮 液,40.0,40.55,39.99,40.32,40.3,-0.3,-0.7444,0.3357,241700,9704480.8,12800000000.0,2880000000.0
9950,1998-10-09,'000858,五 粮 液,40.78,41.3,40.7,41.0,40.7,0.08,0.1966,0.3044,219182,8988578.86,13049600000.0,2936160000.0
9958,1998-09-25,'000858,五 粮 液,40.4,40.5,39.88,39.9,39.88,0.52,1.3039,0.3248,233853,9373225.19,12928000000.0,2908800000.0
10055,1998-05-13,'000858,五 粮 液,63.85,65.75,63.01,63.2,63.43,0.42,0.6621,1.9348,1393048,89469272.65,20432000000.0,4597200000.0